branches:
  only:
  - master
  - testing

language: cpp

dist: xenial

addons:
  apt:
    update: true

matrix:
  include:
  - name: "SGpp-travis-minimal"
    addons:
      apt:
        packages:
        - scons
    script:
    - scons -j 2 SG_PYTHON=0 SG_JAVA=0 RUN_CPP_EXAMPLES=1
  - name: "SGpp-travis-package"
    addons:
      apt:
        packages:
        - fakeroot
        - scons
        - swig
        - python3-dev
        - python3-numpy
        - python3-jinja2
        - libgomp1
        - doxygen
    script:
    - bash tools/travis_scripts/create_deb_install_deb_and_test.sh
  - name: "SGpp-travis-medium"
    addons:
      apt:
        packages:
        - libboost-test-dev
        - scons
        - swig
        - python3-dev
        - python3-numpy
        - openjdk-8-jdk
        - doxygen
    script:
    - scons -j 2 SG_ALL=0 SG_BASE=1 SG_PYTHON=1 SG_JAVA=1 RUN_CPP_EXAMPLES=1 RUN_PYTHON_EXAMPLES=1
  - name: "SGpp-travis-full"
    addons:
      apt:
        packages:
        - libboost-test-dev
        - scons
        - swig
        - python3-dev
        - python3-numpy
        - openjdk-8-jdk
        - doxygen
        - graphviz
        - libgsl-dev
        - zlib1g-dev
        - libeigen3-dev
        - libsuitesparse-dev
        - libarmadillo-dev
        - libgmm++-dev
    script:
    - scons -j 2 RUN_CPP_EXAMPLES=1 RUN_PYTHON_EXAMPLES=1
